name: pro-lab

networks:
  pro-lab:

services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:latest
    networks:
      - pro-lab

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - pro-lab

  loki:
    container_name: loki
    image: grafana/loki:latest
    networks:
      - pro-lab