version: "3.9"

networks:
  pro-lab:

volumes:
  app-static:
  db-data:
  grafana-data:
  loki-data:

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - app-static:/usr/share/nginx/html:ro
    depends_on:
      - api
      - app
      - grafana
    networks:
      - pro-lab

  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - pro-lab

  loki:
    container_name: loki
    image: grafana/loki:latest
    environment:
      - LOKI_CONFIG=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki
    networks:
      - pro-lab

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    networks:
      - pro-lab

  api:
    container_name: prolab-api
    image: pro-lab-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - OPENROUTE_USER_TOKEN=${OPENROUTE_USER_TOKEN}
      - DB_CONNECTION_STRING=Server=db,1433;Database=ProLab;User ID=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=True;Connect Timeout=60;
    depends_on:
      - db
    networks:
    - pro-lab

  app:
    container_name: prolab-app
    image: pro-lab-app:latest
    volumes:
      - app-static:/app
    environment:
      - BlazorEnvironment=Production
    networks:
      - pro-lab
