name: CI-Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: .build
      run: dotnet restore

    - name: Build
      working-directory: .build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      working-directory: ./.build
      run: dotnet test --no-build --verbosity normal
