name: CI

on:
  pull_request:
    branches:
      - main  # Specify your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./.build/ProLab.sln

    - name: Build
      run: dotnet build ./.build/ProLab.sln --configuration Release --no-restore

